import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./src/components/Header/page";
import Footer from "./src/components/Footer/page";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}



